theme: jekyll-theme-minimal
title: Docker 101
updated: 3.1.2024
logo: assets/img/docker-logo.png
show_downloads: False
navigation:
  - title: Overview
    url: /
  - title: 1. Deploy ToDo stand-alone
    url: workshop/lab1
  - title: 2. Update the app, build a new image
    url: workshop/lab2
  - title: 3. Persisiting the data, Volumes
    url: workshop/lab3
  - title: 4. Add MySQL DB, Multi-Container apps
    url: workshop/lab4
  - title: 5. Image Building Best Practises
    url: workshop/lab5
  - title: 6. Tips and useful commands
    url: workshop/lab6    


